// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// osrm_route
Rcpp::List osrm_route(double& xlon, double& xlat, double& ylon, double& ylat, std::string& osmfile, const std::string& algo);
RcppExport SEXP _OSRcppM_osrm_route(SEXP xlonSEXP, SEXP xlatSEXP, SEXP ylonSEXP, SEXP ylatSEXP, SEXP osmfileSEXP, SEXP algoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double& >::type xlon(xlonSEXP);
    Rcpp::traits::input_parameter< double& >::type xlat(xlatSEXP);
    Rcpp::traits::input_parameter< double& >::type ylon(ylonSEXP);
    Rcpp::traits::input_parameter< double& >::type ylat(ylatSEXP);
    Rcpp::traits::input_parameter< std::string& >::type osmfile(osmfileSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type algo(algoSEXP);
    rcpp_result_gen = Rcpp::wrap(osrm_route(xlon, xlat, ylon, ylat, osmfile, algo));
    return rcpp_result_gen;
END_RCPP
}
// osrm_minutes
double osrm_minutes(double& xlon, double& xlat, double& ylon, double& ylat, std::string& osmfile, const std::string& algo);
RcppExport SEXP _OSRcppM_osrm_minutes(SEXP xlonSEXP, SEXP xlatSEXP, SEXP ylonSEXP, SEXP ylatSEXP, SEXP osmfileSEXP, SEXP algoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double& >::type xlon(xlonSEXP);
    Rcpp::traits::input_parameter< double& >::type xlat(xlatSEXP);
    Rcpp::traits::input_parameter< double& >::type ylon(ylonSEXP);
    Rcpp::traits::input_parameter< double& >::type ylat(ylatSEXP);
    Rcpp::traits::input_parameter< std::string& >::type osmfile(osmfileSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type algo(algoSEXP);
    rcpp_result_gen = Rcpp::wrap(osrm_minutes(xlon, xlat, ylon, ylat, osmfile, algo));
    return rcpp_result_gen;
END_RCPP
}
// osrm_miles
double osrm_miles(double& xlon, double& xlat, double& ylon, double& ylat, std::string& osmfile, const std::string& algo);
RcppExport SEXP _OSRcppM_osrm_miles(SEXP xlonSEXP, SEXP xlatSEXP, SEXP ylonSEXP, SEXP ylatSEXP, SEXP osmfileSEXP, SEXP algoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double& >::type xlon(xlonSEXP);
    Rcpp::traits::input_parameter< double& >::type xlat(xlatSEXP);
    Rcpp::traits::input_parameter< double& >::type ylon(ylonSEXP);
    Rcpp::traits::input_parameter< double& >::type ylat(ylatSEXP);
    Rcpp::traits::input_parameter< std::string& >::type osmfile(osmfileSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type algo(algoSEXP);
    rcpp_result_gen = Rcpp::wrap(osrm_miles(xlon, xlat, ylon, ylat, osmfile, algo));
    return rcpp_result_gen;
END_RCPP
}
// osrm_route_vec
Rcpp::NumericVector osrm_route_vec(Rcpp::NumericVector& xlon, Rcpp::NumericVector& xlat, Rcpp::NumericVector& ylon, Rcpp::NumericVector& ylat, std::string& osmfile, const std::string& measure, const std::string& algo);
RcppExport SEXP _OSRcppM_osrm_route_vec(SEXP xlonSEXP, SEXP xlatSEXP, SEXP ylonSEXP, SEXP ylatSEXP, SEXP osmfileSEXP, SEXP measureSEXP, SEXP algoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type xlon(xlonSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type xlat(xlatSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type ylon(ylonSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type ylat(ylatSEXP);
    Rcpp::traits::input_parameter< std::string& >::type osmfile(osmfileSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type measure(measureSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type algo(algoSEXP);
    rcpp_result_gen = Rcpp::wrap(osrm_route_vec(xlon, xlat, ylon, ylat, osmfile, measure, algo));
    return rcpp_result_gen;
END_RCPP
}
// osrm_short
Rcpp::DataFrame osrm_short(Rcpp::NumericVector& xid, Rcpp::NumericVector& xlon, Rcpp::NumericVector& xlat, Rcpp::NumericVector& yid, Rcpp::NumericVector& ylon, Rcpp::NumericVector& ylat, std::string& osmfile, const std::string& measure, const std::string& algo);
RcppExport SEXP _OSRcppM_osrm_short(SEXP xidSEXP, SEXP xlonSEXP, SEXP xlatSEXP, SEXP yidSEXP, SEXP ylonSEXP, SEXP ylatSEXP, SEXP osmfileSEXP, SEXP measureSEXP, SEXP algoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type xid(xidSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type xlon(xlonSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type xlat(xlatSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type yid(yidSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type ylon(ylonSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type ylat(ylatSEXP);
    Rcpp::traits::input_parameter< std::string& >::type osmfile(osmfileSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type measure(measureSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type algo(algoSEXP);
    rcpp_result_gen = Rcpp::wrap(osrm_short(xid, xlon, xlat, yid, ylon, ylat, osmfile, measure, algo));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_OSRcppM_osrm_route", (DL_FUNC) &_OSRcppM_osrm_route, 6},
    {"_OSRcppM_osrm_minutes", (DL_FUNC) &_OSRcppM_osrm_minutes, 6},
    {"_OSRcppM_osrm_miles", (DL_FUNC) &_OSRcppM_osrm_miles, 6},
    {"_OSRcppM_osrm_route_vec", (DL_FUNC) &_OSRcppM_osrm_route_vec, 7},
    {"_OSRcppM_osrm_short", (DL_FUNC) &_OSRcppM_osrm_short, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_OSRcppM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
