# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

osrm_route <- function(xlon, xlat, ylon, ylat, osmfile, algo = "CH") {
    .Call(`_OSRcppM_osrm_route`, xlon, xlat, ylon, ylat, osmfile, algo)
}

osrm_minutes <- function(xlon, xlat, ylon, ylat, osmfile, algo = "CH") {
    .Call(`_OSRcppM_osrm_minutes`, xlon, xlat, ylon, ylat, osmfile, algo)
}

osrm_miles <- function(xlon, xlat, ylon, ylat, osmfile, algo = "CH") {
    .Call(`_OSRcppM_osrm_miles`, xlon, xlat, ylon, ylat, osmfile, algo)
}

osrm_route_vec <- function(xlon, xlat, ylon, ylat, osmfile, measure = "miles", algo = "CH") {
    .Call(`_OSRcppM_osrm_route_vec`, xlon, xlat, ylon, ylat, osmfile, measure, algo)
}

osrm_short <- function(xid, xlon, xlat, yid, ylon, ylat, osmfile, measure = "miles", algo = "CH") {
    .Call(`_OSRcppM_osrm_short`, xid, xlon, xlat, yid, ylon, ylat, osmfile, measure, algo)
}

