# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
osrm_route <- function(xlon, xlat, ylon, ylat, osmfile, algo = "CH") {
    .Call('_OSRcppM_osrm_route', PACKAGE = 'OSRcppM', xlon, xlat, ylon, ylat, osmfile, algo)
}

#' @export
osrm_minutes <- function(xlon, xlat, ylon, ylat, osmfile, algo = "CH") {
    .Call('_OSRcppM_osrm_minutes', PACKAGE = 'OSRcppM', xlon, xlat, ylon, ylat, osmfile, algo)
}

osrm_miles <- function(xlon, xlat, ylon, ylat, osmfile, algo = "CH") {
    .Call('_OSRcppM_osrm_miles', PACKAGE = 'OSRcppM', xlon, xlat, ylon, ylat, osmfile, algo)
}

#' @export
osrm_route_vec <- function(xlon, xlat, ylon, ylat, osmfile, measure = "miles", algo = "CH") {
    .Call('_OSRcppM_osrm_route_vec', PACKAGE = 'OSRcppM', xlon, xlat, ylon, ylat, osmfile, measure, algo)
}

#' @export
osrm_short <- function(xid, xlon, xlat, yid, ylon, ylat, osmfile, measure = "miles", algo = "CH") {
    .Call('_OSRcppM_osrm_short', PACKAGE = 'OSRcppM', xid, xlon, xlat, yid, ylon, ylat, osmfile, measure, algo)
}

